// <auto-generated />
using System;
using BoynerCase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoynerCase.Migrations
{
    [DbContext(typeof(UrunKategoriDbContext))]
    partial class UrunKategoriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoynerCase.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriIsmi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kategori_ismi");

                    b.HasKey("Id")
                        .HasName("PK__kategori__3213E83F26F1F3DB");

                    b.ToTable("kategori", (string)null);
                });

            modelBuilder.Entity("BoynerCase.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    b.Property<string>("UrunIsmi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("urun_ismi");

                    b.HasKey("Id")
                        .HasName("PK__urun__3213E83FF311EAC3");

                    b.HasIndex("KategoriId");

                    b.ToTable("urun", (string)null);
                });

            modelBuilder.Entity("BoynerCase.Models.Urun", b =>
                {
                    b.HasOne("BoynerCase.Models.Kategori", "Kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .HasConstraintName("FK__urun__kategori_i__38996AB5");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BoynerCase.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
